.github/workflows/ci.yaml:
  env:
    - DOCKER_IMAGE: adorsys/node
      TAG: 12-ubi-8
      DIR: ubi-8/12
      ALIASES: '12 12-ubi'
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/node
      TAG: 14-ubi-8
      DIR: ubi-8/14
      ALIASES: '14 14-ubi'
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/node
      TAG: 16-ubi-8
      DIR: ubi-8/16
      ALIASES: '16 16-ubi'
      SQUASH: 'true'
