.github/workflows/ci.yaml:
  checkoutTestApplications: true
  env:
    - DOCKER_IMAGE: adorsys/node
      TAG: 10-ubi-8
      DIR: ubi-8/10
      ALIASES: '10 10-ubi'
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/node
      TAG: 12-ubi-8
      DIR: ubi-8/12
      ALIASES: '12 12-ubi'
      SQUASH: 'true'
    - DOCKER_IMAGE: adorsys/node
      TAG: 14-ubi-8
      DIR: ubi-8/12
      ALIASES: '14 14-ubi'
      SQUASH: 'true'
