.github/workflows/ci.yaml:
  checkoutTestApplications: true
  env:
    - DOCKER_IMAGE: adorsys/node
      TAG: 10-centos
      DIR: centos/10
      ALIASES: "10"
    - DOCKER_IMAGE: adorsys/node
      TAG: 12-centos
      DIR: centos/12
      ALIASES: "12"
    - DOCKER_IMAGE: adorsys/node
      TAG: 10-ubi
      DIR: ubi/10
    - DOCKER_IMAGE: adorsys/node
      TAG: 12-ubi
      DIR: ubi/12
